version: '3.8'

services:
  # Servicio para la aplicación Flask
  web:
    build: ./app
    container_name: flask
    restart: always
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - DATABASE_URI=mysql+pymysql://avq:5122000@db:3306/database
    volumes:
      - ./app:/app
    depends_on:
      - db

  # Servicio para Nginx
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

  # Servicio para la base de datos MySQL
  db:
    image: mysql:9.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Sudo5122000
      MYSQL_DATABASE: avqdb
      MYSQL_USER: avq
      MYSQL_PASSWORD: 5122000
    volumes:
      - db_data:/var/lib/mysql

# Volumenes persistentes
volumes:
  db_data:
