services:
  web:
    build: ./app
    container_name: flask
    restart: always
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=${FLASK_ENV} 
      - FLASK_DEBUG=${FLASK_DEBUG}
      - DATABASE_URI=${DATABASE_URI}
    volumes:
      - ./app:/app
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

  db:
    image: mysql:9.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf

volumes:
  db_data: